test:
  dialect: mysql
  datasource: user:pass@tcp(localhost:3314)/gte_test?parseTime=true
  dir: internal/interface/database/migration
  table: migrations

development:
  dialect: mysql
  datasource: user:pass@tcp(localhost:3314)/gte_dev?parseTime=true
  dir: internal/interface/database/migration
  table: migrations
